[package]

name = "silva"
version = "0.0.1"
authors = [ "Stephen M. Williams <steve.williams7@ntlworld.com>" ]

[profile.release]
opt-level = 3

[[bin]]

name = "silva"

[dependencies]

chrono="0.2"
bit-vec="*"
itertools="*"
